name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install Frozen-Flask

    - name: Freeze Flask application
      run: python freeze.py

    - name: Print freeze.py output
      run: cat freeze.py

    - name: List working directory contents
      run: |
        ls -la
        if diff -r --no-dereference . ./build; then
          exit 0
        else
          rsync -avH --delete-after . ./build
        fi

    - name: List build directory contents
      run: ls -la ./build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Ensure this matches the output directory of Frozen-Flask